apiVersion: v1
kind: ReplicationController
metadata:
  name: cache-server
spec:
  replicas: 1
  selector:
    app: nginx-cache-server
  template:
    metadata:
      name: cache-server
      labels:
        app: nginx-cache-server
    spec:
      containers:
      - name: cache-server
        image: gcr.io/sonic-column-220616/cache-server:v2
        ports:
        - containerPort: 3128